# Generated by Django 4.1.3 on 2022-12-07 19:01

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Imóvel', 'verbose_name_plural': 'Imóveis'},
        ),
        migrations.RenameField(
            model_name='district',
            old_name='state',
            new_name='city',
        ),
        migrations.AlterField(
            model_name='property',
            name='cover',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='cover', variations={'thumb': {'crop': True, 'height': 350, 'width': 300}}, verbose_name='Imagem'),
        ),
    ]
