# Generated by Django 3.2 on 2022-08-15 19:50

from django.db import migrations, models
import django.utils.timezone
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='ctagory',
            new_name='category',
        ),
        migrations.AddField(
            model_name='property',
            name='imagem_01',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='Property', variations={'thumb': {'crop': True, 'height': 520, 'width': 770}}, verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='property',
            name='imagem_02',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='Property', variations={'thumb': {'crop': True, 'height': 520, 'width': 770}}, verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='property',
            name='imagem_03',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='Property', variations={'thumb': {'crop': True, 'height': 520, 'width': 770}}, verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='property',
            name='imagem_04',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='Property', variations={'thumb': {'crop': True, 'height': 520, 'width': 770}}, verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='property',
            name='imagem_05',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='Property', variations={'thumb': {'crop': True, 'height': 520, 'width': 770}}, verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='property',
            name='plant',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='Plant', variations={'thumb': {'crop': True, 'height': 337, 'width': 439}}, verbose_name='Planta'),
        ),
        migrations.AddField(
            model_name='property',
            name='type_property',
            field=models.CharField(choices=[('sale', 'Venda'), ('rent', 'Aluguel')], default=django.utils.timezone.now, max_length=255, verbose_name='Venda ou Aluguel?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='Agent', variations={'thumb': {'crop': True, 'height': 70, 'width': 70}}, verbose_name='Imagem'),
        ),
    ]
