# Generated by Django 3.2 on 2022-08-15 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220815_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='imagem',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='imagem_01',
            new_name='image_01',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='imagem_02',
            new_name='image_02',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='imagem_03',
            new_name='image_03',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='imagem_04',
            new_name='image_04',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='imagem_05',
            new_name='image_05',
        ),
    ]
