# Generated by Django 3.2 on 2022-12-05 15:52

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220815_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image_01',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_02',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_03',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_04',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_05',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='Property', variations={'thumb': {'crop': True, 'height': 520, 'width': 770}}, verbose_name='Imagem')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.property')),
            ],
        ),
    ]
